Techfest_2k18/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include, re_path
import main_page.views
from . import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', main_page.views.index),
    path('', main_page.views.redirect_to_index, name="home"),
    path('events', main_page.views.display_events, name="events"),
    path('event/<slug:event_name>', main_page.views.event_info, name="event info"),
    path('registration/', include('registration.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('password_reset/', auth_views.password_reset, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('reset/(<uidb64>/<token>', auth_views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
    path('contact-us', main_page.views.contact_us, name="contact_us"),
    # ----
    # TEMPORARY
    path('tempeventinfo', main_page.views.temp_event_info),
    # ------

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    path('profile', views.redirect_to_profile_home, ),
    path('profile/', views.redirect_to_profile_home),
    path('profile/edit', views.edit_info, name="edit_additional_info"),
    path('profile/home', views.profile_home, name="profile_home"),
    path('updates', views.updates, name="updates"),
    path('login/', auth_views.login, name="login"),
    path('event/<slug:event_name>/register', views.register_user_for_event, name="register_for_event"),
    path('event/<slug:event_name>/deregister', views.un_register_user_for_event, name="un_register_for_event"),
    path('myevents', views.display_user_registered_events, name="myevents"),
    path('maps', views.maps, name="map"),
    path('calender', views.calender, name="calender"),
    path('password-change', views.change_password, name="change_password"),
    path('profile/qr-code', views.disp_qr_code, name="disp_qr_code")
]

api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token
from .views import EventsList, MoreUserDataView, RegisteredOrNotView, AllRegisteredEventsView, RegisterUserView, GoogleLogin

app_name = "api"

urlpatterns = [
    path('api-token-auth', obtain_jwt_token),
    path('EventsList', EventsList.as_view(), name="EventsList"),
    path('MoreUserDataView', MoreUserDataView.as_view(), name="MoreUserDataView"),
    path('GoogleLogin', GoogleLogin.as_view(), name="GoogleLogin"),
    path('RegisteredOrNotView', RegisteredOrNotView.as_view(), name="RegisteredOrNotView"),
    path('RegisterUserView', RegisterUserView.as_view(), name="RegisterUserView"),
    path('AllRegisteredEventsView', AllRegisteredEventsView.as_view(), name="AllRegisteredEventsView"),
]

registration/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = "registration"

urlpatterns = [
    path('signup', views.signup, name="signup"),
    path('login', auth_views.login, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('account-activation-email-sent', views.account_activation_email_sent, name='account_activation_email_sent'),
    path('activate/<uidb64>/<token>', views.activate_account, name='activate'),
    path('resend-activation-link', views.generate_new_activation_link, name='resend_activation_link'),

]

accounts/views.py
import datetime

import pytz
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from data.models import MoreUserData, Event
from django.contrib.auth.models import User
from data.forms import EditProfileMoreUserDataInfo, EditProfileUserInfo, ChangePasswordForm, UpdateTemplateForm
from django.contrib.auth.decorators import login_required
from main_page.forms import EventRegisterForm
from django.contrib.auth import login
import os.path
# For encryption
import hashlib
# The QR code file
from . import QRcode

# Create your views here.


secret_string = ''


def email_confirmation_required(func):
    """
    A decorator which allows to access url only if email for current user has been confirmed.
    THE DECORATOR login_required MUST ALWAYS PRECEDE THIS

    """

    def checker(request, *args, **kwargs):
        if request.user.emailconfirmation.email_confirmed is True:
            return func(request, *args, **kwargs)

        else:
            return render(request, "accounts/email_not_verified.html")

    return checker


def MD5encrypt(str1):
    str1 = str(str1)
    str2 = 'ksbdyemxl'
    str3 = 'snaoheiwmsceqf'
    str4 = str2 + str1 + str3

    result = hashlib.md5(str4.encode())

    return result.hexdigest()


def redirect_to_profile_home(request):
    return redirect('accounts:profile_home')


def get_user_details(request):
    user_details = {"username": request.user.username,
                    "fullname": request.user.get_full_name(),
                    }

    if hasattr(request.user, 'moreuserdata'):

        S = str(request.user.moreuserdata.profile_pic)
        if S is not '':
            user_details["profile_pic"] = request.user.moreuserdata.profile_pic.url
        else:
            user_details["profile_pic"] = '/media/profile_pictures/default/blank.jpg'
    else:
        user_details["profile_pic"] = '/media/profile_pictures/default/blank.jpg'

    return user_details


@login_required
@email_confirmation_required
def profile_home(request):
    user_details = get_user_details(request)
    if hasattr(request.user, "moreuserdata"):
        user_details["details_check"] = True
        MUD = request.user.moreuserdata
        user_details["about"] = MUD.description
        user_details["college"] = MUD.college_name
        user_details["email"] = request.user.email
        user_details["phone_number"] = str(MUD.country_code) + ' ' + str(MUD.phone_number)
        user_details["github_id"] = MUD.github_id
        user_details["hackerrank_id"] = MUD.hackerrank_id
        user_details["codechef_id"] = MUD.codechef_id
        user_details["codeforces_id"] = MUD.codeforces_id


    return render(request, "accounts/profile_home.html", {"active_profile": True, "profile": user_details})


@login_required
@email_confirmation_required
def edit_info(request):
    current_user_details = get_user_details(request)
    current_user_details["is_profile_pic_set"] = True
    if current_user_details["profile_pic"] == '/media/profile_pictures/default/blank.jpg':
        current_user_details["is_profile_pic_set"] = False
        current_user_details["edit_profile_pic"] = '/media/profile_pictures/default/add_pic.jpeg'
    if request.method == "POST":

        user_data_form = EditProfileUserInfo(request.POST)
        more_user_data_form = EditProfileMoreUserDataInfo(request.POST, request.FILES)

        if user_data_form.is_valid():
            U = request.user
            U.first_name = user_data_form.cleaned_data['first_name']
            U.last_name = user_data_form.cleaned_data['last_name']
            U.save()

        if more_user_data_form.is_valid():

            MUD = None
            if hasattr(request.user, 'moreuserdata'):
                MUD = request.user.moreuserdata
            else:
                MUD = MoreUserData()
                MUD.user = request.user
                # Encryption
                MUD.secret_key = MD5encrypt(request.user.username)
                # Using the variable secret_string to send to qrcode
                secret_string = str(MUD.secret_key)

            MUD.college_name = more_user_data_form.cleaned_data["college_name"]
            MUD.country_code = more_user_data_form.cleaned_data["country_code"]
            MUD.phone_number = more_user_data_form.cleaned_data["phone_number"]
            MUD.description = more_user_data_form.cleaned_data["description"]
            MUD.github_id = more_user_data_form.cleaned_data["github_id"]
            MUD.hackerrank_id = more_user_data_form.cleaned_data["hackerrank_id"]
            MUD.codechef_id = more_user_data_form.cleaned_data["codechef_id"]
            MUD.codeforces_id = more_user_data_form.cleaned_data["codeforces_id"]
            MUD.tshirt_size = more_user_data_form.cleaned_data["tshirt_size"]

            if "profile_pic" in request.FILES:
                MUD.profile_pic = request.FILES["profile_pic"]

            MUD.save()
            return redirect('accounts:profile_home')

        else:
            return render(request, "accounts/edit_info.html",
                          {"user_data_form": user_data_form,
                           "more_user_data_form": more_user_data_form,
                           "profile": current_user_details,
                           })

    else:
        new_user_data_form = EditProfileUserInfo(instance=request.user)
        if hasattr(request.user, 'moreuserdata'):
            new_more_user_data_form = EditProfileMoreUserDataInfo(instance=request.user.moreuserdata)

        else:
            new_more_user_data_form = EditProfileMoreUserDataInfo()

        return render(request, "accounts/edit_info.html",
                      {"user_data_form": new_user_data_form,
                       "more_user_data_form": new_more_user_data_form,
                       "profile": current_user_details,
                       })


@login_required
@email_confirmation_required
def display_user_registered_events(request):
    user_details = get_user_details(request)
    event_set = request.user.moreuserdata.participating_events.all()
    return_event_set = list()
    localtimezone = pytz.timezone('Asia/Kolkata')
    cur_datetime = datetime.datetime.now()
    cur_datetime = localtimezone.localize(cur_datetime)
    for event in event_set:
        E = {"name": event.name.title(), }
        if event.start_date_time > cur_datetime:
            diff = event.start_date_time - cur_datetime
            if diff.days > 0:
                E["start_diff"] = "Starts In " + str(diff.days) + " Days"
            else:
                E["start_diff"] = "Starts In " + str(diff.seconds) + " Seconds"
        elif event.end_date_time > cur_datetime:
            diff = event.end_date_time - cur_datetime
            if diff.days > 0:
                E["end_diff"] = "Ends In " + str(diff.days) + " Days"
            else:
                E["end_diff"] = "Ends In " + str(diff.seconds) + " Seconds"

        if str(event.logo) is not "":
            E["logo"] = event.logo.url

        return_event_set.append(E)
    return render(request, "accounts/myevents.html",
                  {"profile": user_details,
                   "active_events": True,
                   "events": return_event_set,
                   "default_logo": "/media/events/defaults/logo.png"
                   }
                  )


@login_required
@email_confirmation_required
def register_user_for_event(request, event_name):
    try:
        event_name = str(event_name)
    except ValueError:
        return render(request, "accounts/invalid_request.html")

    if not hasattr(request.user, 'moreuserdata'):
        return render(request, "accounts/invalid_request.html", {
            "message": "Your Profile is missing some critical information. Please go to your profile and fill out the missing information before registering for the event",
            "links": ["incomplete_profile"]})

    event_name = event_name.lower().replace('-', ' ')
    if request.method == 'POST':
        register_form = EventRegisterForm(request.POST)

        if register_form.is_valid():
            if request.user.username == register_form.cleaned_data["username"]:
                if event_name == register_form.cleaned_data["event"]:
                    event = get_object_or_404(Event, name=event_name)
                    if request.user.moreuserdata in event.participants.all():
                        return render(request, "accounts/invalid_request.html",
                                      {"message": "You are already registered for this event"})
                    else:
                        event.participants.add(request.user.moreuserdata)
                else:
                    return render(request, "accounts/invalid_request.html", {"message": "Invalid request"})
            else:
                return render(request, "accounts/invalid_request.html", {"message": "Invalid request"})
        else:
            return render(request, "accounts/invalid_request.html", {"message": "Invalid request"})

        return render(request, "accounts/registration_complete.html",
                      {"username": register_form["username"].value(), "event": register_form['event'].value()})
    else:
        return render(request, "accounts/invalid_request.html", {"message": "Invalid request"})


@login_required
@email_confirmation_required
def un_register_user_for_event(request, event_name):
    event_slug = event_name
    try:
        event_name = str(event_name)
    except ValueError:
        return render(request, "accounts/invalid_request.html", {"message": "Invalid request"})

    if not hasattr(request.user, 'moreuserdata'):
        return render(request, "accounts/invalid_request.html", {"message": "Invalid request"})

    event_name = event_name.lower().replace('-', ' ')
    if request.method == 'POST':
        register_form = EventRegisterForm(request.POST)

        if register_form.is_valid():

accounts/templates/accounts/calendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/calender.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/email_not_verified.html
{% extends "data/basic_message_template.html" %}
{% load static %}
    {% comment %}
        THIS IS AN EXTENTION TEMPLATE.
        MAKE SURE THAT EVERYTHING IS WITHIN THE RESPECTIVE BLOCK ELEMENTS.
        ANYTHING OUTSIDE A BLOCK ELEMENT WILL NOT BE RENDERED

        {% block %}
            ..      THIS IS A BLOCK ELEMENT
        {% endblock %}

        NOTE: Load static is purposefully kept out of block
    {% endcomment %}

{% block load_files %}
    {% comment %}
    Load custom filters,app_files etc. here (DJANGO RELATED)
    {% endcomment %}
{% endblock load_files %}


<!-- Head Start -->
    {% block title %}
        {% comment %}
            SET THE TITLE OF THE PAGE HERE
        {% endcomment %}
        Activation Email
    {% endblock title %}


    {% block stylesheets %}
        {% comment %}
            Import required stylesheets here.
            font-awesome.min.css is already imported
        {% endcomment %}
        <link>
    {% endblock stylesheets %}


    {% block javascript_files %}
        {% comment %}
            Import required javascript files here.
            jquery.min.js is already imported
        {% endcomment %}
        <script></script>
    {% endblock javascript_files %}


    {% block style %}
        {% comment %}
        Add Custom Styles Here
        {% endcomment %}
        <style>

        </style>
    {% endblock style %}


    {% block scripts %}
        {% comment %}
        Add Custom Scripts Here that need to be added in head.
        Scripts that need to added at the end of file should be put in the block element at the end of this file
        {% endcomment %}
        <script>

        </script>
    {% endblock scripts %}


<!-- Head End -->


<!-- Body Starts -->

    {% block background_image %}
        <img src="{% static 'registration/images/sat.jpeg' %}">
    {% endblock background_image %}

    {% block section1_img1 %}
        <i class="fa fa-envelope" style="font-size: 50px;"></i>
    {% endblock section1_img1 %}

    {% block section1_content1 %}
       It seems your email has not been confirmed.<br>
       Click on the account activation link in your email<br>
       <a href="{% url 'registration:resend_activation_link' %}">Generate a new link</a>
    {% endblock section1_content1 %}

    {% block eofscripts %}
        {% comment %}
            All the scripts tht should be at the end of file should be put here
        {% endcomment %}
        <script>

        </script>
    {% endblock eofscripts %}
<!-- Body End -->

accounts/templates/accounts/invalid_request.html
{% extends "data/basic_message_template.html" %}
{% load static %}
    {% comment %}
        THIS IS AN EXTENTION TEMPLATE.
        MAKE SURE THAT EVERYTHING IS WITHIN THE RESPECTIVE BLOCK ELEMENTS.
        ANYTHING OUTSIDE A BLOCK ELEMENT WILL NOT BE RENDERED

        {% block %}
            ..      THIS IS A BLOCK ELEMENT
        {% endblock %}

        NOTE: Load static is purposefully kept out of block
    {% endcomment %}

{% block load_files %}
    {% comment %}
    Load custom filters,app_files etc. here (DJANGO RELATED)
    {% endcomment %}
{% endblock load_files %}


<!-- Head Start -->
    {% block title %}
        {% comment %}
                SET THE TITLE OF THE PAGE HERE
            {% endcomment %}
        Activation Email
    {% endblock title %}


    {% block stylesheets %}
        {% comment %}
                Import required stylesheets here.
                font-awesome.min.css is already imported
            {% endcomment %}
        <link>
    {% endblock stylesheets %}


    {% block javascript_files %}
        {% comment %}
                Import required javascript files here.
                jquery.min.js is already imported
            {% endcomment %}
        <script></script>
    {% endblock javascript_files %}


    {% block style %}
        {% comment %}
            Add Custom Styles Here
            {% endcomment %}
        <style>

        </style>
    {% endblock style %}


    {% block scripts %}
        {% comment %}
            Add Custom Scripts Here that need to be added in head.
            Scripts that need to added at the end of file should be put in the block element at the end of this file
            {% endcomment %}
        <script>

        </script>
    {% endblock scripts %}


<!-- Head End -->


<!-- Body Starts -->

    {% block background_image %}
        <img src="{% static 'registration/images/sat.jpeg' %}">
    {% endblock background_image %}

    {% block section1_img1 %}
        <i class="fa fa-envelope" style="font-size: 50px;"></i>
    {% endblock section1_img1 %}

    {% block section1_content1 %}
        {{ message }} <br><br>
        {% if links %}

            {% if 'incomplete_profile' in links %}
                Go To <a href="{% url 'accounts:edit_additional_info' %}">Fill Additional Info</a><br>
            {% endif %}

        {% endif %}
        Redirect To <a href={% url 'home' %}>home</a>
    {% endblock section1_content1 %}

<!-- Body End -->

accounts/templates/accounts/profile_home.html
{% extends 'accounts/profile_skelton.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Profile
{% endblock title %}

{% block content %}
    <div class="col s12 m9 l9 center grey darken-2">
        <div class="row">
            <img src="{{ profile.profile_pic }}" class='circle responsive-img row1' alt="">
            <div class="user_fullname">
                {{ profile.fullname }}
            </div>
            <div class="user_username">
                @{{ profile.username }}
            </div>

        </div>
        <div class="row">
            <ul class="collection">
                {% if profile.details_check %}
                    <li class="collection-item left-align">
                        About :
                        <span>{{ profile.about }}</span>
                    </li>
                    <li class="collection-item left-align">
                        Institute :
                        <span>{{ profile.college }}</span>
                    </li>
                    <li class="collection-item left-align">
                        <ul class="collapsible z-depth-1">
                            <li>
                                <div class="collapsible-header"><i
                                        class="material-icons">filter_drama</i><span>Connect</span></div>
                                <div class="collapsible-body">
                                    <ul class="collection">
                                        <li class="collection-item">Github : {{ profile.github_id }}</li>
                                        <li class="collection-item">CodeChef : {{ profile.codechef_id }}</li>
                                        <li class="collection-item">HackerRank : {{ profile.hackerrank_id }}</li>
                                        <li class="collection-item">Codeforces : {{ profile.codeforces_id }}</li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </li>

                    <li class="collection-item left-align">
                        <div class="row">
                            Contact :
                        </div>
                        <div class="row center">
                            <div class="col s12 m6 l6">
                                Email : {{ profile.email }}
                            </div>
                            <div class="col s12 m6 l6">
                                Phone : {{ profile.phone_number }}
                            </div>
                        </div>
                    </li>

                {% else %}

                    <li class="collection-item left-align">
                        About :
                        <span>Not Set Yet</span>
                    </li>
                    <li class="collection-item left-align">
                        Institute :
                        <span>Not Set Yet</span>
                    </li>
                    <li class="collection-item left-align">
                        <ul class="collapsible z-depth-1">
                            <li>
                                <div class="collapsible-header"><i
                                        class="material-icons">filter_drama</i><span>Connect</span></div>
                                <div class="collapsible-body">
                                    <ul class="collection">
                                        <li class="collection-item">Github : ----</li>
                                        <li class="collection-item">CodeChef : ----</li>
                                        <li class="collection-item">HackerRank : ----</li>
                                        <li class="collection-item">Codeforces : ----</li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </li>

                    <li class="collection-item left-align">
                        <div class="row">
                            Contact :
                        </div>
                        <div class="row center">
                            <div class="col s12 m6 l6">
                                Email : {{ profile.email }}
                            </div>
                            <div class="col s12 m6 l6">
                                Phone : Not Set
                            </div>
                        </div>
                    </li>

                {% endif %}

                <li class="collection-item left-align">
                    <div class="row">
                        <div class="col s12 m4 l4">
                            <a href="{% url 'accounts:edit_additional_info' %}"><button name="button" class="btn">Edit Profile</button></a>
                        </div>
                        <div class="col s12 m4 l4">
                            <a href="{% url 'accounts:change_password' %}"><button name="button" class="btn">Change Password</button></a>
                        </div>
                        <div class="col s12 m4 l4">
                            <a href="{% url 'accounts:disp_qr_code' %}" download><button name="button" class="btn">Download QR Code</button></a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endblock content %}



{% comment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav>
    <a>Logo</a> |
    <a href="{% url 'accounts:myevents' %}">My Events</a> |
    <a>Teams</a> |
    <a href="{% url 'accounts:edit_additional_info' %}">Edit Profile</a> |
    <a href="{% url 'accounts:profile_home' %}">Hello {{ user.username }}</a> |
    <a href="{% url 'registration:logout' %}">Logout</a><br><br>

</nav>
{% if additional_info_check %}
    {% if not user.profile_pic %}
        You haven't set a profile pic yet. <a href="{% url 'accounts:edit_additional_info' %}">Click Here</a> to set one
    {% else %}
        Great. You are all all done
    {% endif %}
{% else %}
    Your Account seems to be missing some critical info. <a href="{% url 'accounts:edit_additional_info' %}">Click here</a> to add missing information
{% endif %}
</body>
</html>

{% endcomment %}

accounts/templates/accounts/profile_skelton.html
{% load static %}
{% load widget_tweaks %}

{% block load_files %}
{% endblock load_files %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Title
        {% endblock title %}
    </title>
    <link rel="shortcut icon" type="image/x-icon" href="{{ profile.profile_pic }}" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'accounts/css/materialize.min.css' %}" media="screen,projection"/>

    {% block stylesheets %}
    {% endblock stylesheets %}

    {% block javascript_files %}
    {% endblock javascript_files %}

    <style media="screen">
        img {
            height: 100px;
            width: 100px;
        }

        /* .container > div > div:nth-child(odd) {
            background: #333;
        }
        .container > div > div:nth-child(even) {
            background: #666;
        } */

        .row1 {
            margin-top: 20px;
        }

        .flex {
            display: flex;
            flex-wrap: wrap;
        }

        .header {
            height: 10vh;
            background-color: red;
        }

        .footer {
            height: 10vh;
            background-color: yellow;
            width: 100%;
        }

        .user_fullname {
            font-weight: bold;
            font-size: 120%;
        }

        .user_username {
            font-style: italic;
        }

        .left_panel_text {
            font-weight: bold;
            font-size: 150%;
        }

        .topnav {
            overflow: hidden;
            background-color: #333;
        }

        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        .topnav a.active {
            background-color: #4CAF50;
            color: white;
        }
    </style>
    {% block style %}
    {% endblock style %}

    {% block scripts %}
    {% endblock scripts %}
</head>
<body>

{% block header %}
    <div class="header topnav">
          <a class="active" href="#">Sample Placeholder Nav Bar</a>
          <a href="#">Option</a>
          <a href="#">Option</a>
          <a href="#">option</a>
    </div>
{% endblock header %}

<div class="row flex">
    {% block left_panel %}
        <div class="col s12 m3 l3 center first-col black darken-2 red-text">
            <div class="row">
                <img src="{{ profile.profile_pic }}" class='circle responsive-img row1' alt="">
                <div class="user_fullname">
                    {{ profile.fullname }}
                </div>
                <div class="user_username">
                    @{{ profile.username }}
                </div>
            </div>
            <div class="row card-panel left_panel_text {% if not active_updates %}black darken{% endif %}">
                <a href="{% url 'accounts:updates' %}" class="{% if active_updates %} black-text {% else %}white-text {% endif %}">
                    Updates
                </a>
            </div>
            <div class="row card-panel left_panel_text {% if not active_profile %}black darken{% endif %}">
                <a href="{% url 'accounts:profile_home' %}" class="{% if active_profile %} black-text {% else %}white-text {% endif %}">
                    My Profile
                </a>
            </div>
            <div class="row card-panel left_panel_text {% if not active_events %}black darken{% endif %}">
                <a href="{% url 'accounts:myevents' %}" class="{% if active_events %} black-text {% else %}white-text {% endif %}">
                    My Events
                </a>
            </div>

            <div class="row card-panel left_panel_text {% if not active_settings %}black darken{% endif %}">
                <a href="#" class="{% if active_settings %} black-text {% else %}white-text {% endif %}">
                    Settings
                </a>
            </div>
        </div>
    {% endblock left_panel %}

    {% block content %}

    {% endblock content %}
</div>

{% block footer %}
    <div class="footer">
        Space left for footer
    </div>
{% endblock footer %}


<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static 'accounts/js/materialize.min.js' %}"></script>

<script>
    $(document).ready(function () {
        $('.dropdown-button').dropdown({
            constrainWidth: false,
            hover: true,
            belowOrigin: true,
            alignment: 'left'
        });

        // JAVASCRIPT START HERE //

    });
</script>
{% block endscripts %}
{% endblock endscripts %}
</body>

</html>

accounts/templates/accounts/qr_code.html
{% load qr_code %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QRCOde</title>
</head>
<body style="text-align: center">
{% qr_from_text secret_string size="m" image_format="png" error_correction="L" %}
</body>
</html>