Techfest_2k18/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include, re_path
import main_page.views
from . import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', main_page.views.index),
    path('', main_page.views.redirect_to_index, name="home"),
    path('events', main_page.views.display_events, name="events"),
    path('event/<slug:event_name>', main_page.views.event_info, name="event info"),
    path('registration/', include('registration.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('password_reset/', auth_views.password_reset, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('reset/(<uidb64>/<token>', auth_views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
    path('contact-us', main_page.views.contact_us, name="contact_us"),
    # ----
    # TEMPORARY
    path('tempeventinfo', main_page.views.temp_event_info),
    # ------

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    path('profile', views.redirect_to_profile_home, ),
    path('profile/', views.redirect_to_profile_home),
    path('profile/edit', views.edit_info, name="edit_additional_info"),
    path('profile/home', views.profile_home, name="profile_home"),
    path('updates', views.updates, name="updates"),
    path('login/', auth_views.login, name="login"),
    path('event/<slug:event_name>/register', views.register_user_for_event, name="register_for_event"),
    path('event/<slug:event_name>/deregister', views.un_register_user_for_event, name="un_register_for_event"),
    path('myevents', views.display_user_registered_events, name="myevents"),
    path('maps', views.maps, name="map"),
    path('calender', views.calender, name="calender"),
    path('password-change', views.change_password, name="change_password"),
    path('profile/qr-code', views.disp_qr_code, name="disp_qr_code")
]

api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token
from .views import EventsList, MoreUserDataView, RegisteredOrNotView, AllRegisteredEventsView, RegisterUserView, GoogleLogin

app_name = "api"

urlpatterns = [
    path('api-token-auth', obtain_jwt_token),
    path('EventsList', EventsList.as_view(), name="EventsList"),
    path('MoreUserDataView', MoreUserDataView.as_view(), name="MoreUserDataView"),
    path('GoogleLogin', GoogleLogin.as_view(), name="GoogleLogin"),
    path('RegisteredOrNotView', RegisteredOrNotView.as_view(), name="RegisteredOrNotView"),
    path('RegisterUserView', RegisterUserView.as_view(), name="RegisterUserView"),
    path('AllRegisteredEventsView', AllRegisteredEventsView.as_view(), name="AllRegisteredEventsView"),
]

main_page/forms.py
from django import forms


class EventRegisterForm(forms.Form) :
    username = forms.CharField(widget=forms.HiddenInput())
    event = forms.CharField(widget=forms.HiddenInput())

main_page/views.py
from django.shortcuts import render, redirect, get_object_or_404

import data.models
import data.forms
import data.defaults
import datetime
import pytz
from .forms import EventRegisterForm

# Create your views here.

month_to_word = {1: "Janury",
                 2: "February",
                 3: "March",
                 4: "April",
                 5: "May",
                 6: "June",
                 7: "July",
                 8: "August",
                 9: "September",
                 10: "October",
                 11: "November",
                 12: "December"
                 }


def get_required_date_time_data(start_date, end_date, utc_start_date, utc_end_date):
    if not isinstance(start_date, datetime.datetime):
        raise ValueError("Received start-date is not an instance of datetime.datetime")

    if not isinstance(end_date, datetime.datetime):
        raise ValueError("Received end-date is not an instance of datetime.datetime")

    retmonth = month_to_word[start_date.month]
    retdate = start_date.day
    retdate = str(retdate)
    retdatesupscript = "th"
    if retdate[-1] == '1':
        retdatesupscript = "st"
    elif retdate[-1] == '2':
        retdatesupscript = "nd"
    elif retdate[-1] == '3':
        retdatesupscript = "rd"

    rettime_block = "AM"
    rethour = start_date.hour
    retmin = start_date.minute

    if start_date.hour > 12:
        rethour -= 12
        rettime_block = "PM"

    retmin = start_date.minute

    duration = utc_end_date - utc_start_date
    retdiffdays = duration.days
    diffsec = duration.seconds
    retdiffhours = diffsec // 3600
    diffsec -= (retdiffhours * 3600)
    retdiffminutes = diffsec // 60

    retfinaldiff = ""
    if retdiffdays:
        if retdiffdays == 1:
            retfinaldiff += str(retdiffdays) + " Day" + " "
        else:
            retfinaldiff += str(retdiffdays) + " Days" + " "
    if retdiffhours:
        retfinaldiff += str(retdiffhours) + " Hours" + " "

    if not retfinaldiff:
        retfinaldiff = str(retdiffminutes) + " Minutes"
    else:
        if retdiffminutes:
            retfinaldiff += str(retdiffminutes) + " Minutes"

    return {"month": retmonth,
            "date": retdate,
            "datesuperscript": retdatesupscript,
            "timeblock": rettime_block,
            "hour": rethour,
            "minute": retmin,
            "diff": retfinaldiff
            }


def index(request):
    render_dict = {}

    if request.user.is_authenticated:
        username = request.user.username
        render_dict["username"] = username

    events = list()
    for event in data.models.Event.objects.all():
        E = {"name": event.name.title()}
        if str(event.logo):
            E["logo"] = event.logo.url
        if hasattr(event, 'eventcatalogue'):
            if str(event.eventcatalogue.image1):
                E["prime_image"] = event.eventcatalogue.image1.url

        localtimezone = pytz.timezone('Asia/Kolkata')
        local_start_date_time = event.start_date_time.astimezone(localtimezone)
        local_end_date_time = event.start_date_time.astimezone(localtimezone)
        E["calender"] = get_required_date_time_data(local_start_date_time, local_end_date_time, event.start_date_time,
                                                    event.end_date_time)
        events.append(E)

    render_dict["events"] = events
    render_dict["event_coming_soon_image"] = '/media/events/defaults/coming_soon.jpg'
    render_dict["default_logo"] = '/media/events/defaults/logo.png'
    return render(request, "main_page/index.html", render_dict)


def redirect_to_index(request):
    return redirect('/index')


def display_events(request):
    catagories = [c.name for c in data.models.EventCatagory.objects.all()]
    events = list()
    for i in data.models.Event.objects.all():
        event = dict()
        event["name"] = i.name.title()
        event["catagories"] = [xx.name for xx in i.catagories.all()]
        if str(i.logo) is "":
            event["logo"] = data.defaults.event_logo
        else:
            event["logo"] = i.logo.url

        events.append(event)

    return render(request, "main_page/events.html", {"events": events, "catagories": catagories})


def event_info(request, event_name):
    event_info_page = 'main_page/K_event_info.html'
    event_name = event_name.lower()
    event_slug = event_name
    event_name = event_name.replace('-', ' ')

    event = get_object_or_404(data.models.Event, name=event_name)
    event_duration = event.end_date_time - event.start_date_time
    event_duration_string = ""
    if event_duration.days > 0:
        event_duration_string += " " + str(event_duration.days) + " Days"
    if event_duration.seconds//3600 > 0:
        event_duration_string += " " + str(event_duration.seconds//3600) + " Hours"
    if (event_duration.seconds % 3600)//60 > 0:
        event_duration_string += " " + str((event_duration.seconds % 3600)//60) + " Minutes"

    event_organisers = event.organisers.all()
    event_logo = data.defaults.event_logo
    if str(event.logo):
        event_logo = event.logo.url

    event_catalogue = list()
    if hasattr(event, 'eventcatalogue'):
        if event.eventcatalogue.image1.name:
            event_catalogue.append(event.eventcatalogue.image1.url)

            if event.eventcatalogue.image2.name:
                event_catalogue.append(event.eventcatalogue.image2.url)

                if event.eventcatalogue.image3.name:
                    event_catalogue.append(event.eventcatalogue.image3.url)

                    if event.eventcatalogue.image4.name:
                        event_catalogue.append(event.eventcatalogue.image4.url)

                        if event.eventcatalogue.image5.name:
                            event_catalogue.append(event.eventcatalogue.image5.url)

                            if event.eventcatalogue.image6.name:
                                event_catalogue.append(event.eventcatalogue.image6.url)

        else:
            event_catalogue.append(data.defaults.event_prime_catalogue)
    else:
        event_catalogue.append(data.defaults.event_prime_catalogue)

    if request.user.is_authenticated:
        registerform = EventRegisterForm({"username": request.user.username, "event": event_name})
        if hasattr(request.user, "moreuserdata"):
            if event.participants.all().filter(pk=request.user.moreuserdata.user_id).exists():
                return render(request, event_info_page,
                              {"event": event, "organisers": event_organisers, "logo": event_logo,
                               "catalogue": event_catalogue,
                               "duration": event_duration_string,
                               "authenticated": True,
                               "registerform": registerform, "event_slug": event_slug, "registered": True})

            else:
                return render(request, event_info_page,
                              {"event": event, "organisers": event_organisers, "logo": event_logo,
                               "catalogue": event_catalogue,
                               "duration": event_duration_string,
                               "authenticated": True,
                               "registerform": registerform, "event_slug": event_slug, "registered": False})

        return render(request, event_info_page,
                      {"event": event, "organisers": event_organisers, "logo": event_logo,
                       "catalogue": event_catalogue,
                       "duration": event_duration_string,
                       "authenticated": True,
                       "registerform": registerform, "event_slug": event_slug})

    else:
        return render(request, event_info_page,
                      {"event": event, "organisers": event_organisers,
                       "logo": event_logo,
                       "duration": event_duration_string,
                       "catalogue": event_catalogue,
                       })


def contact_us(request):
    return render(request, "main_page/contact_us.html")


def temp_event_info(request):
    return render(request, "main_page/event_info.html")

main_page/templates/main_page/contact_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact-Us</title>
</head>
<body>

</body>
</html>

main_page/templates/main_page/event_info.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="shortcut icon" href="{% static 'main_page/img/icons/icon-ctf-logo.png' %}" />
<link href="{% static 'main_page/css/timeline.css' %}" rel="stylesheet" >				<!-- Custom CSS of event page -->
<link href="{% static 'main_page/css/main.css' %}" rel="stylesheet"> 					<!-- Custom styles for this template -->
<link href="{% static 'main_page/css/jR3D-style.css' %}" rel="stylesheet">					<!-- CSS file for slider -->
<link href="{% static 'main_page/css/style.css' %}" rel="stylesheet">


<!-- UIkit -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/css/uikit.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.6/js/uikit-icons.min.js"></script>


<!-- Bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



<!-- Slider -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.0/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="{% static 'main_page/js/jR3DCarousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main_page/js/jR3Djsfile.js' %}"></script>



<style>

body
{
	background: url( "{% static 'main_page/img/page/ctf-log.jpg' %}");
	background-repeat: no-repeat;
	background-attachment:fixed;
	background-size: cover;
}


/* The circles on the timeline */
.container-event::after {
    content: '';
    position: absolute;
    width: 25px;
    height: 25px;
    right: -17px;
	background: url('{% static "main_page/img/icons/icon-ctf.png" %}' ) center center no-repeat;
    border: 4px solid #FF9F55;
    top: 15px;
    border-radius: 50%;
    z-index: 1;
}


.box-1
{
	background: url('{% static "main_page/img/page/ctf1.jpg" %}') center center no-repeat;
	background-size: cover;
	opacity:0.8;
}


.box-2
{
	background: url('{%  static "main_page/img/page/ctf2.jpg" %}') center center no-repeat;
	background-size: cover;
	opacity:0.8;
}



.box-3
{
	background: url('{% static "main_page/img/page/ctf3.jpg" %}') center center no-repeat;
	background-size: cover;
	opacity:0.8;
}


.box-4
{
	background: url('{% static "main_page/img/page/ctf4.jpg" %}') center center no-repeat;
	background-size: cover;
	opacity:0.8;
}


</style>


</head>

<body>

<div style="text-align:center;">
	<div class="chip uk-container" style=" margin:20px; margin-bottom: 5px;">
		<div style="float:left">
			<h3 style="color:#ff5500;">
				<strong>Capture The Flag</strong>
			</h3>
		</div>
	</div>
</div>


<div class="uk-container">	
	<div style="text-align:center;margin:10px;" >
		<img src="{% static 'main_page/img/icons/icon-ctf-logo.png' %}"  width="120" height="120">
	</div>
</div>



<div class="container-slider" style="margin:20px;">
	
		<div class="jR3DCarouselGalleryCustomeTemplate">
			
			<div class="jR3DCarouselCustomSlide">
				<img src="{% static 'main_page/img/page/ctf-c-1.jpg' %}" />
				<div class="captions">This is custom text slide 1</div>
			</div>
			
			<div class="jR3DCarouselCustomSlide">
					<img src="{% static 'main_page/img/page/ctf-c-2.jpg' %}" />
					<span class="captions">This is clickable slide 2</span>				
			</div>
			
			<div class="jR3DCarouselCustomSlide">
				<img src="{% static 'main_page/img/page/ctf-c-3.jpg' %}" />
				<div class="captions">This is custom text slide 3</div>
			</div>
			
			<div class="jR3DCarouselCustomSlide">
				<img src="{% static 'main_page/img/page/ctf-c-4.jpg' %}" />
				<div class="captions">This is custom text slide 4</div>
			</div>
			
			<div class="jR3DCarouselCustomSlide">
				<img src="{% static 'main_page/img/page/ctf-c-5.jpg' %}" />
				<div class="captions">This is custom text slide 5</div>
			</div>
			
		</div>
</div>

<div>
	<div class="timeline" uk-scrollspy="cls: uk-animation-fade;delay: 700; repeat: false">
		  <div class="container-event left" >
				 
		  
				<div class="content box-1" uk-scrollspy="cls: uk-animation-slide-left;delay:500;repeat: true" >
					<div class="col-md-12 col-sm-4">
						<div style="text-align:center;">
							<div class="chip">
								<h3 style="color:#ff5500;font-size:2vw;" ><b>Introduction</b></h3>
							  </div>
						</div>
					</div>
					<p style="color:#F0FFF0;font-size:1vw;color:cyan; " >Lorem ipsum dolor sit amet, quo ei simul congue exerci, ad nec admodum perfecto mnesarchum, vim ea mazim fierent detracto. Ea quis iuvaret expetendis his, te elit voluptua dignissim per, habeo iusto primis ea eam.</p>
				</div>
				
				
				
		  </div>
		  
		  
		  <div class="container-event right">
			<div class="content box-2" uk-scrollspy="cls: uk-animation-slide-right;delay:800;repeat: true" >
				<div class="col-md-12 col-sm-4">
					<div style="text-align:center;">
						<div class="chip">
							<h3 style="color:#ff5500;font-size:2vw;" ><b>Schedule</b></h3>
						</div>
					</div>
				</div>
					<p style="color:#7CFC00;" ><img src="{% static 'main_page/img/icons/icon-cal.png' %}"><strong style="font-size:2vw;"> 26 September 2018 </strong></p>
					<p style="font-size:2vw;color:cyan;" >Timings : <strong style="font-size:2vw;">02:00 PM to 04:00 PM</strong></p>
				<a href="#" class="btn btn-danger btn-rounded li-nav-event" style="background-color:red;"><strong style="font-family: 'Raleway', sans-serif;">Register Now</strong></a>
			</div>
		  </div>
		  
		  
		  
		  
		  
		  
		  <div class="container-event left">
			<div class="content box-3" uk-scrollspy="cls: uk-animation-slide-left;delay:1100;repeat: true">
				<div class="col-md-12 col-sm-4">
					<div style="text-align:center">
						<div class="chip">
							<h3 style="color:#ff5500;"><strong>Prizes</strong></h3>
						</div>
					</div>
				</div>
				<ul type="none" style="font-size:1.5vw;" uk-parallax="opacity: 0,1; y: 100,0; scale: 0.5,1; viewport: 0.5;">
					<li class="li-nav-event" style="color:cyan;" ><img class="li-nav-event" src="{% static 'main_page/img/icons/icon-medal.png' %}" width="40" height="40" style="margin:10px;">Winner : <span style="color:orange;">asdad</span></li>
					<li class="li-nav-event" style="color:cyan;" ><img class="li-nav-event" src="{% static 'main_page/img/icons/icon-medal-silver.png' %}" width="40" height="40" style="margin:10px;">First Runner-Up : <span style="color:orange;">asdad</span></li>
					<li class="li-nav-event" style="color:cyan;" ><img class="li-nav-event" src="{% static 'main_page/img/icons/icon-medal-bronze.png' %}" width="40" height="40" style="margin:10px;">Second Runner-Up : <span style="color:orange;">adsad</span></li>
				</ul>
			</div>
		  </div>
		  
		  <div class="container-event right">
			<div class="content box-4" uk-scrollspy="cls: uk-animation-slide-right;repeat: true">
				<div class="col-md-12 col-sm-4">
					<div style="text-align:center">
						<div class="chip">
							<h3 style="color:#ff5500;font-size:2vw;" ><b>Rules</b></h3>
						</div>
					</div>
				</div>
			  <p style="font-size:1.5vw;color:orange;" uk-parallax="opacity: 0,1; y: 100,0; viewport: 0.5"><strong>Kindly go through Rules and Regulation of the event.</strong></p>
			  <form><a href="#" class="btn btn-danger btn-rounded li-nav-event" style="background-color:red;"><strong style="font-family: 'Raleway', sans-serif;">Click Here</strong></a></form>
			</div>
		  </div>
	</div>  
</div>	  
		  <div class="uk-container-event">
			  <div class="chip" style="margin:20px;"><h3 style="color:#ff5500;"><strong>Help Desk</strong></h3></div>
					<div class="uk-container">
					  <div class="uk-child-width-1-2@s uk-grid-match" uk-grid>
							<div>
								<div class="uk-card uk-card-primary" style="border-radius:40px 40px 40px 40px" uk-scrollspy="cls: uk-animation-slide-left;" uk-scrollspy="cls: uk-animation-fade; delay: 500; repeat: true" uk-parallax="sepia: 70;">
									<img src="{% static 'main_page/img/comments/c1.jpg' %}" class="uk-border-circle uk-align-center" alt="shubh vanvat" width="148" height="148">
									<h3 style="margin-left:25px;" class="uk-card-title uk-margin-remove-bottom;"><strong>Shubh Vanvat</strong></h3>
									<p style="margin-left:25px;" class="uk-text-meta uk-margin-remove-top">Coordinator</p>
									<div class="col-md-6 col-sm-10"style="margin:5px;">
										<img src="{% static 'main_page/img/icons/icon-mail.png' %}"><span style="font-size:1.5vw"><strong> shubh.v17@iiits.in</strong></span>
									</div>
									<div class="col-md-6 col-sm-10">
										<img src="{% static 'main_page/img/icons/icon-phone.png' %}" style="margin-left:20px;"><span style="font-size:1.5vw"><strong>+918989221599</strong></span>
									</div>
								</div>
							</div>
							<div>
								<div class="uk-card uk-card-primary" style="border-radius:40px 40px 40px 40px"  uk-scrollspy="cls: uk-animation-slide-right;" uk-scrollspy="cls: uk-animation-fade; delay: 500; repeat: true" uk-parallax="sepia: 70;">
									<img src="{% static 'main_page/img/comments/c1.jpg' %}" class="uk-border-circle uk-align-center" alt="shubh vanvat" width="148" height="148">
									<h3 style="margin-left:25px;" class="uk-card-title uk-margin-remove-bottom;"><strong>Shubh Vanvat</strong></h3>
									<p style="margin-left:25px;" class="uk-text-meta uk-margin-remove-top">Coordinator</p>
									<div class="col-md-6 col-sm-10"style="margin:5px;">
										<img src="{% static 'main_page/img/icons/icon-mail.png' %}"><span style="font-size:1.5vw"><strong> shubh.v17@iiits.in</strong></span>
									</div>
									<div class="col-md-6 col-sm-10">
										<img src="{% static 'main_page/img/icons/icon-phone.png' %}" style="margin-left:20px;"><span style="font-size:1.5vw"><strong>+918989221599</strong></span>
									</div>
								</div>
							</div>
							<div>
								<div class="uk-card uk-card-primary" style="border-radius:40px 40px 40px 40px"  uk-scrollspy="cls:uk-animation-fade; delay: 500; repeat: true; uk-animation-slide-left;" uk-parallax="sepia: 70;">
									<img src="{% static 'main_page/img/comments/c1.jpg' %}" class="uk-border-circle uk-align-center" alt="shubh vanvat" width="148" height="148">
									<h3 style="margin-left:25px;" class="uk-card-title uk-margin-remove-bottom;"><strong>Shubh Vanvat</strong></h3>
									<p style="margin-left:25px;" class="uk-text-meta uk-margin-remove-top">Coordinator</p>
									<div class="col-md-6 col-sm-10"style="margin:5px;">
										<img src="{% static 'main_page/img/icons/icon-mail.png' %}"><span style="font-size:1.5vw"><strong> shubh.v17@iiits.in</strong></span>
									</div>
									<div class="col-md-6 col-sm-10">
										<img src="{% static 'main_page/img/icons/icon-phone.png' %}" style="margin-left:20px;"><span style="font-size:1.5vw"><strong>+918989221599</strong></span>
									</div>
								</div>
							</div>
							<div>
								<div class="uk-card uk-card-primary" style="border-radius:40px 40px 40px 40px"  uk-scrollspy="cls:uk-animation-fade; delay: 500; repeat: true; uk-animation-slide-right;" uk-parallax="sepia: 70;">
									<img src="{% static 'main_page/img/comments/c1.jpg' %}" class="uk-border-circle uk-align-center" alt="shubh vanvat" width="148" height="148">
									<h3 style="margin-left:25px;" class="uk-card-title uk-margin-remove-bottom;"><strong>Shubh Vanvat</strong></h3>
									<p style="margin-left:25px;" class="uk-text-meta uk-margin-remove-top">Coordinator</p>
									<div class="col-md-6 col-sm-10"style="margin:5px;">
										<img src="{% static 'main_page/img/icons/icon-mail.png' %}"><span style="font-size:1.5vw"><strong> shubh.v17@iiits.in</strong></span>
									</div>
									<div class="col-md-6 col-sm-10">
										<img src="{% static 'main_page/img/icons/icon-phone.png' %}" style="margin-left:20px;"><span style="font-size:1.5vw"><strong>+918989221599</strong></span>
									</div>
								</div>
							</div>
					</div>
				</div>

          </div>
</body>
</html>



main_page/templates/main_page/footer.html
							{% load static %}

<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> <!-- Bootstrap -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css"> <!-- materialise -->
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> <!-- Google fonts : Raleway -->
	

    <link href="{% static 'main_page/css/bootstrap.min.css' %}" rel="stylesheet">			<!-- Bootstrap CSS -->
    <link href="{% static 'main_page/css/font-awesome.min.css' %}" rel="stylesheet">		<!-- Fonts Icon CSS -->
    <link href="{% static 'main_page/css/et-line.css' %}" rel="stylesheet">				<!-- Fonts Icon CSS -->
    <link href="{% static 'main_page/css/ionicons.min.css' %}" rel="stylesheet">			<!-- Fonts Icon CSS -->
    <link rel="stylesheet" href="{% static 'main_page/css/animate.min.css' %}">			<!-- Animate CSS -->
    <link href="{% static 'main_page/css/main.css' %}" rel="stylesheet"> 					<!-- Custom styles for this template -->

</head>



	
													<!--footer start -->

													
<body>					
	<footer>
		<div class="container">
			<div class="row justify-content-center">

				<div class="col-md-4 col-12">
					<div class="footer_box" style="margin-top:0px">
						
						<div class="footer_box_body" >
							<h5 class="title color-light">
								Stay Tuned With All Updates At:-
							</h5>
							<ul class="footer_social">
								<li>
									<a href="#"><i class="ion-social-googleplus"></i></a>
								</li>
								<li>
									<a href="#"><i class="ion-social-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="ion-social-twitter"></i></a>
								</li>
								
								
							</ul>
						</div>
					</div>
				</div>

				<div class="col-12 col-md-4">
					<div class="footer_box">
						
					</div>
				</div>

				<div class="col-12 col-md-4">
					<div class="footer_box" style="margin-top:0px">
						<div class="footer_header">
							<h4 class="footer_title">
								Query ? Feel Free To Ping Us At
							</h4>
						</div>
						<div class="footer_box_body">
							<div class="newsletter_form">
								
								<button class="btn btn-rounded btn-block btn-primary"><strong>programming@iiits.in</strong></button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<div class="copyright_footer">
		<div class="container">
			<div class="row justify-content-center">
			   
				<div class="col-12 col-md-6 ">
					<ul class="footer_menu">
						<li>
							<a href="#"><strong>Home</strong></a>
						</li>
						
						<li>
							<a href="#"><strong>About</strong></a>
						</li>
						
						<li>
							<a href="#"><strong>Events</strong></a>
						</li>
						
						<li>
							<a href="#"><strong>Comments</strong></a>
						</li>
						
						<li>
							<a href="#"><strong>Event-Calender</strong></a>
						</li>
						
						<li>
							<a href="#"><strong>Sponsors</strong></a>
						</li>
						
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!--footer end -->



</body>
</html>

main_page/templates/main_page/temp_event_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ event.name }}<br>
{% if logo %}
Logo Url : {{ logo }}<br>
{% else %}
No Logo Available<br>
{% endif %}

{{ event.start_date_time }}<br>
{{ event.end_date_time }}<br>
<hr>
{% if authenticated %}
    {% if registered %}
        <form action="{% url 'accounts:un_register_for_event' event_slug %}" method="post">
            {% csrf_token %}
            {{ registerform }}
            <input type="submit" value="De-Register">
        </form>
    {% else %}
        <form action="{% url 'accounts:register_for_event' event_slug %}" method="post">
            {% csrf_token %}
            {{ registerform }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
{% else %}
You must sign in to be able to register
{% endif %}
<hr>
Description :<br>
{{ event.description }}
<hr>
Rules: <br>
{{ event.rules }}
<hr>
Prizes: <br>
{{ event.prize }}
<hr>
Organisers : <br>

{% for O in organisers %}
    {{ O.user.get_full_name }}
{% endfor %}
<br><br>
Here we can also add more parameters for organisers like profile pictures username etc..
</body>
</html>